function insult() {
	local INSULTS=(
		"You type like I drive.",
		"You speak an infinite deal of nothing",
		"I wish to make a complaint.",
		"What kind of mutant ninja are you ?",
		"DAMN !!! And you call yourself a PRO!",
		"(╯°□°）╯",
		"What, what, what, what, what, what, what, what, what, what?",
		"Are you on drugs?",
		"Your mind just hasn't been the same since the electro-shock, has it?",
		"Commands, random gibberish, who cares!",
		"My cat can type better than you?",
		"Try using your brain the next time!",
		"I fart in your general direction!",
		"What if... you type an actual command the next time!",
		"Are you always this stupid or are you making a special effort today?!",
		"I am _seriously_ considering 'rm -rf /'-ing myself...",
		"This is not a search engine.",
		"stty: unknown mode: doofus",
		"Perhaps computers is not for you...",
		"There must be cure for it!",
		"Where did you learn to type?",
		"What do you think you are doing, idiot?",
		"Why are you doing this to me?!",
		"Please step away from the keyboard!",
		"If I wanted to kill myself I'd climb your ego and jump to your IQ.",
		"Wrong!  You cheating scum!",
		"Hold it up to the light --- not a brain in sight!",
		"What if I told you... it is possible to type valid commands.",
		"I bet your brain feels as good as new, seeing that you never use it.",
		"So, I'm just going to go ahead and run rm -rf / for you.",
		"You do that again and see what happens...",
		"Bailing out, you are on your own. Good luck! ",
		"error code: 1D10T",
		"I'd like to see things from your point of view but I can't seem to get my head that far up my ass.",
		"buh, buh, buh... Get to it, idiot!",
		"I'm not saying I hate you, but I would unplug your life support to charge my phone.",
		"I think ... err ... I think ... I think you must go home",
		"ERROR_INCOMPETENT_USER",
		"Speak English you fool --- there are no subtitles in this scene.",
		"The keyboard is not a touch screen!",
		"I've seen penguins that can type better than that.",
		"Incompetence is also a form of competence",
		"It can only be attributed to human error.",
		"Did someone dropped you while you were a baby, eh?",
		"Take a stress pill and think things over."
		"Boooo!"
		"Don't you know anything?"
		"RTFM!"
		"Hahaha, n00b!"
		"Wow! That was impressively wrong!"
		"What are you doing??"
		"Pathetic"
		"The worst one today!"
		"n00b alert!"
		"Your application for reduced salary has been sent!"
		"lol"
		"u suk"
		"lol... plz"
		"plz uninstall"
		"And the Darwin Award goes to.... ${USER}!"
		"ERROR_INCOMPETENT_USER"
		"Incompetence is also competence"
		"Bad."
		"Fake it till you make it!"
		"What is this...? Amateur hour!?"
		"Come on! You can do it!"
		"Nice try."
		"What if... you type an actual command the next time!"
		"What if I told you... it is possible to type valid commands."
		"Y u no speak computer???"
		"This is not Windows"
		"Perhaps you should leave the command line alone..."
		"Please step away from the keyboard!"
		"error code: 1D10T"
		"ACHTUNG! ALLES TURISTEN UND NONTEKNISCHEN LOOKENPEEPERS! DAS KOMPUTERMASCHINE IST NICHT FÜR DER GEFINGERPOKEN UND MITTENGRABEN! ODERWISE IST EASY TO SCHNAPPEN DER SPRINGENWERK, BLOWENFUSEN UND POPPENCORKEN MIT SPITZENSPARKEN. IST NICHT FÜR GEWERKEN BEI DUMMKOPFEN. DER RUBBERNECKEN SIGHTSEEREN KEEPEN DAS COTTONPICKEN HÄNDER IN DAS POCKETS MUSS. ZO RELAXEN UND WATSCHEN DER BLINKENLICHTEN."
		"Pro tip: type a valid command!"
		"Go outside."
		"This is not a search engine."
		"So, I'm just going to go ahead and run rm -rf / for you."
		"Why are you so stupid?!"
		"Perhaps computers is not for you..."
		"Why are you doing this to me?!"
		"Don't you have anything better to do?!"
		"I am _seriously_ considering 'rm -rf /'-ing myself..."
		"This is why you get to see your children only once a month."
		"This is why nobody likes you."
		"Are you even trying?!"
		"The village called, they want their idiot back."
		"I once owned a dog that was smarter than you."
		"You fight like a dairy farmer."
		"I've spoken to apes more polite than you."
		"Go and boil your bottom! Son of a silly person!"
		"Go away or I shall taunt you a second time."
		"You are a sad, strange little man, and you have my pity."
		"You're dumber than a bag of hammers."
		"If you ever tax your brain, don't charge more than a penny."
		"Don't you have a terribly empty feeling ---- in your skull?"
		"People like you are the reason I'm on medication."
		"Don't let your mind wander. It's way too small to be outside by itself!"
		"Hey, Remember that time I told you I thought you were cool? I LIED."
		"I have always wondered why people bang their heads against brick walls..... then I met you. Don't bother leaving a message."
		"I had a nightmare. I dreamt I was you."
		"Everyone is entitled to be stupid, but you abuse the privilege."
		"There are some stupid people in this world. You just helped me realize it."
		"Cancel my subscriptions ... I'm tired of your issues."
		"Earth is full. Go home."
		"Hey, heres a hint. If i don't answer you the first 25 times, what makes you think the next 25 will work?"
		"I'm not mean ... you're just a sissy."
		"Sorry I can't think of an insult stupid enough for you."
		"Calling you an idiot would be an insult to all the stupid people."
		"Well, they do say opposites attract...so I sincerely hope you meet somebody who is attractive, honest, intelligent, and cultured..."
		"Is your name Maple Syrup? It should be, you sap."
		"Are you always this stupid or are you just making a special effort today?"
		"If I could be a real person for a day, it sure as hell wouldn't be you."
		"You know, you are a classic example of the inverse ratio between the size of the mouth and the size of the brain."
		"You clinking, clanking, clattering collection of caliginous junk!"
		"To call you stupid would be an insult to stupid people! I've known sheep that could outwit you. I've worn dresses with higher IQs."
		"Freaking idiot."
		"Well, I'll tell you something that should be of vital interest to you. That you, sir, are a NITWIT!"
		"Don't get uncool and heavy on me now."
		"You would bore the leggings off a village idiot."
		"You're a tool, you're a weapon, you're a monster, you're a toy, you're a toy-monster, you're a toy-monster-monster."
		"I'm not a fan of you, but I'll take you up on that."
		"You are a pathetic excuse for a person."
		"Slubberdegullion!"
		"Patagonian!"
		"Vampire!"
		"Sycophant!"
		"Kleptomaniac!"
		"Egoist!"
		"Tramp!"
		"Monopolizer!"
		"Pockmark!"
		"Belemnite!"
		"Crook!"
		"Miserable earthworm!"
		"Coconut!"
		"Harlequin!"
		"Parasite!"
		"Macrocephalic baboon!"
		"Brute!"
		"Pirate!"
		"Doryphore!"
		"Gobbledygook!"
		"Filibuster!"
		"Guano gatherer!"
		"Pachyrhizus!"
		"Toad!"
		"Gyroscope!"
		"Bougainvillea!"
		"Bloodsucker!"
		"Nincompoop!"
		"Shipwrecker!"
		"Cyclone!"
		"Gallows-fodder!"
		"Politician!"
		"Baboon!"
		"Torturer!"
		"Fuzzy-wuzzy!"
		"Blackbird!"
		"Mountebank!"
		"Cannibal!"
		"Duck-billed platypus!"
		"Black-beetle!"
		"Rhizopod!"
		"Ruffian!"
		"Vermicelli!"
		"Lily-livered bandicoot!"
		"Rat!"
		"Logarithm!"
		"Cro-Magnon!"
		"Freshwater swab!"
		"Beast!"
		"Bully!"
		"Anthropophagus!"
		"Pithecanthropus!"
		"Savage!"
		"Gangster!"
		"Wrecker!"
		"Vandal!"
		"Carpet-seller!"
		"Numbskull!"
		"Gang of thieves!"
		"Slave-trader!"
		"Picaroon!"
		"Visigoth!"
		"Toffee-nose!"
		"Anacoluthon!"
		"Hydrocarbon!"
		"Technocrat!"
		"Buccaneer!"
		"Traitor!"
		"Caterpillar!"
		"Odd-toed ungulate!"
		"Woodlice!"
		"Swine!"
		"Blackguard!"
		"Vegetarian!"
		"Dizzard!"
		"Fancy-dress freebooter!"
		"Centipede!"
		"Sea-lice!"
		"Ectoplasm!"
		"Fat face!"
		"Artichoke!"
		"Troglodyte!"
		"Turncoat!"
		"Bashi-bazouk!"
		"Olympic Athlete!"
		"Ectoplasmic Byproduct!"
		"Balkan Beetle!"
		"Two-timing Tartar Twister!"
		"Terrapin!"
		"Breathalyser!"
		"Profiteer!"
		"Abecedarian!"
		"Vulture!"
		"Pyrographer!"
		"Phylloxera!"
		"Dog!"
		"Hooligan!"
		"Steamroller!"
		"Body-snatcher!"
		"Ostrogoth!"
		"Brigand!"
		"Heretic!"
		"Anthracite!"
		"Black marketeer!"
		"Ophicleide!"
		"Dynamiter!"
		"Pickled herrings!"
		"Gibbering ghost!"
		"Corsair!"
		"Moujik!"
		"Bootlegger!"
		"Goggler!"
		"Villain!"
		"Aborigine!"
		"Bagpiper!"
		"Crab-apple!"
		"Goosecap!"
		"Aztec!"
		"Paranoiac!"
		"Twister!"
		"Vagabond!"
		"Sea-gherkin!"
		"Road-hog!"
		"Hi-jacker!"
		"Zapotec!"
		"Cercopithecus!"
		"Psychopath!"
		"Rattlesnake!"
		"Jellied-eel!"
		"Liquorice!"
		"Coelacanth!"
		"Invertebrate!"
		"Nyctalop!"
		"Mameluke!"
		"Dipsomaniac!"
		"Diplodocus!"
		"Coward!"
		"Megalomaniac!"
		"Highwayman!"
		"Autocrat!"
		"Bandit!"
		"Nitwit!"
		"Polygraph!"
		"Iconoclast!"
		"Orangoutang!"
		"Squawking popinjay!"
		"Prattling porpoise!"
		"Scoffing braggart!"
		"Murderer!"
		"Rotten sand-hopper!"
		"Billions of bilious blue blistering barnacles!"
		"Ten Thousand Thundering Typhoons!"
		"Anamorphic aardvark!"
		"Anachronism!"
		"Addle-pated lumps of anthracite!"
		"Blithering bombardier!"
		"Thundering son of a sea-gherkin!"
		"Rapscallion!"
		"Arabesque!"
		"Lubberly scum!"
		"Insolent porcupine!"
		"Dunderheaded coconut!"
		"Jobbernowl!"
		"Anthropithecus!"
		"Arabian nightmare!"
		"Misguided missile!"
		"Megacycle!"
		"Pyromaniac!"
		"Big-head!"
		"Poltroon!"
		"Brontosaurus!"
		"Dunder-headed Ethelred!"
		"Prize purple jelly-fish!"
		"Jack-pudding!"
		"Interplanetary goat!"
		"Ku-Klux-Klan!"
		"Cyclotron!"
		"Bully!"
		"Moth-eaten marmot!"
		"Fancy-dress fascist!"
		"Bonehead!"
		"Cut-throat!"
		"Viper!"
		"Gallows-bird!"
		"Interplanetary-pirate!"
		"Freshwater-spaceman!"
		"Prize Nincompoop!"
		"Scorpion!"
		"Unfeeling Monster!"
		"Weevil!"
		"Dictatorial duck billed diplodocus!"
		"Puffed up punchinello!"
		"Thundering herd of zapotecs!"
		"Borgia!"
		"Miserable blundering barbecued blister . . . (Haddock does not complete the curse)"
		"Subtropical sea louse!"
		"Confounded rattletrap!"
		"Tin-can contraption!"
		"Stool-pigeon!"
		"Tribe of savages!"
		"Monster!"
		"Band of thugs!"
	)
	if $INSULTS_OFFENSIVE_ENABLED; then
		INSULTS+=(
			"You're about as much use as a condom machine in the Vatican."
			"You are the son of a motherless ogre."
			"I fart in your general direction. Your mother was a hamster and your father smelled of elderberries."
			"Bite my shiny metal ass!"
			"Up yours, meatbag."
			"Don't piss me off today, I'm running out of places to hide the bodies..."
			"Why don't you go outside and play hide and go fuck yourself!"
			"I'll use small words you're sure to understand, you warthog-faced buffoon."
			"Sit your five dollar ass down before I make change."
			"Why don't you go back to your home on Whore Island?"
			"If I had a dick this is when I'd tell you to suck it."
			"Go play in traffic."
			"When you pass away and people ask me what the cause of your death was, I'll say your stupidity."
			"Roses are red, violets are blue, i have 5 fingers and the middle one is for You."
			"Right now I'm sitting here looking at you trying to see things from your point of view but I can't get my head that far up my ass."
			"If you're gonna act like a dick you should wear a condom on your head so you can at least look like one !!!"
			"Oh I'm sorry, how many times did your parents drop you when you were a baby?"
			"God made mountains, god made trees, god made you but we all make mistakes."
			"Remember JESUS loves you but everyone else thinks you're an idiot."
		)
	fi

	printf "$(tput setaf 3)$(shuf -n 1 -e "${INSULTS[@]}")$(tput sgr0)"
}

# bofh: BOFH style excuses
function excuse() {
	local EXCUSES=(
		"clock speed"
		"solar flares"
		"electromagnetic radiation from satellite debris"
		"static from nylon underwear"
		"static from plastic slide rules"
		"global warming"
		"poor power conditioning"
		"static buildup"
		"doppler effect"
		"hardware stress fractures"
		"magnetic interference from money/credit cards"
		"dry joints on cable plug"
		"we're waiting for [the phone company] to fix that line"
		"sounds like a Windows problem try calling Microsoft support"
		"temporary routing anomaly"
		"somebody was calculating pi on the server"
		"fat electrons in the lines"
		"excess surge protection"
		"floating point processor overflow"
		"divide-by-zero error"
		"POSIX compliance problem"
		"monitor resolution too high"
		"improperly oriented keyboard"
		"network packets travelling uphill (use a carrier pigeon)"
		"Decreasing electron flux"
		"first Saturday after first full moon in Winter"
		"radiosity depletion"
		"CPU radiator broken"
		"It works the way the Wang did what's the problem"
		"positron router malfunction"
		"cellular telephone interference"
		"techtonic stress"
		"piezo-electric interference"
		"(l)user error"
		"working as designed"
		"dynamic software linking table corrupted"
		"heavy gravity fluctuation move computer to floor rapidly"
		"secretary plugged hairdryer into UPS"
		"terrorist activities"
		"not enough memory go get system upgrade"
		"interrupt configuration error"
		"spaghetti cable cause packet failure"
		"boss forgot system password"
		"bank holiday - system operating credits  not recharged"
		"virus attack luser responsible"
		"waste water tank overflowed onto computer"
		"Complete Transient Lockout"
		"bad ether in the cables"
		"Bogon emissions"
		"Change in Earth's rotational speed"
		"Cosmic ray particles crashed through the hard disk platter"
		"Smell from unhygienic janitorial staff wrecked the tape heads"
		"Little hamster in running wheel had coronary; waiting for replacement to be Fedexed from Wyoming"
		"Evil dogs hypnotised the night shift"
		"Plumber mistook routing panel for decorative wall fixture"
		"Electricians made popcorn in the power supply"
		"Groundskeepers stole the root password"
		"high pressure system failure"
		"failed trials system needs redesigned"
		"system has been recalled"
		"not approved by the FCC"
		"need to wrap system in aluminum foil to fix problem"
		"not properly grounded please bury computer"
		"CPU needs recalibration"
		"system needs to be rebooted"
		"bit bucket overflow"
		"descramble code needed from software company"
		"only available on a need to know basis"
		"knot in cables caused data stream to become twisted and kinked"
		"nesting roaches shorted out the ether cable"
		"The file system is full of it"
		"Satan did it"
		"Daemons did it"
		"You're out of memory"
		"There isn't any problem"
		"Unoptimized hard drive"
		"Typo in the code"
		"Yes yes its called a design limitation"
		"Look buddy:  Windows 3.1 IS A General Protection Fault."
		"That's a great computer you have there; have you considered how it would work as a BSD machine?"
		"Please excuse me I have to circuit an AC line through my head to get this database working."
		"Yeah yo mama dresses you funny and you need a mouse to delete files."
		"Support staff hung over send aspirin and come back LATER."
		"Someone is standing on the ethernet cable causing a kink in the cable"
		"Windows 95 undocumented 'feature'"
		"Runt packets"
		"Password is too complex to decrypt"
		"Boss' kid fucked up the machine"
		"Electromagnetic energy loss"
		"Budget cuts"
		"Mouse chewed through power cable"
		"Stale file handle (next time use Tupperware(tm)!)"
		"Feature not yet implemented"
		"Internet outage"
		"Pentium FDIV bug"
		"Vendor no longer supports the product"
		"Small animal kamikaze attack on power supplies"
		"The vendor put the bug there."
		"SIMM crosstalk."
		"IRQ dropout"
		"Collapsed Backbone"
		"Power company testing new voltage spike (creation) equipment"
		"operators on strike due to broken coffee machine"
		"backup tape overwritten with copy of system manager's favourite CD"
		"UPS interrupted the server's power"
		"The electrician didn't know what the yellow cable was so he yanked the ethernet out."
		"The keyboard isn't plugged in"
		"The air conditioning water supply pipe ruptured over the machine room"
		"The electricity substation in the car park blew up."
		"The rolling stones concert down the road caused a brown out"
		"The salesman drove over the CPU board."
		"The monitor is plugged into the serial port"
		"Root nameservers are out of sync"
		"electro-magnetic pulses from French above ground nuke testing."
		"your keyboard's space bar is generating spurious keycodes."
		"the real ttys became pseudo ttys and vice-versa."
		"the printer thinks its a router."
		"the router thinks its a printer."
		"evil hackers from Serbia."
		"we just switched to FDDI."
		"halon system went off and killed the operators."
		"because Bill Gates is a Jehovah's witness and so nothing can work on St. Swithin's day."
		"user to computer ratio too high."
		"user to computer ration too low."
		"we just switched to Sprint."
		"it has Intel Inside"
		"Sticky bits on disk."
		"Power Company having EMP problems with their reactor"
		"The ring needs another token"
		"new management"
		"telnet: Unable to connect to remote host: Connection refused"
		"SCSI Chain overterminated"
		"It's not plugged in."
		"because of network lag due to too many people playing deathmatch"
		"You put the disk in upside down."
		"Daemons loose in system."
		"User was distributing pornography on server; system seized by FBI."
		"BNC (brain not connected)"
		"UBNC (user brain not connected)"
		"LBNC (luser brain not connected)"
		"disks spinning backwards - toggle the hemisphere jumper."
		"new guy cross-connected phone lines with ac power bus."
		"had to use hammer to free stuck disk drive heads."
		"Too few computrons available."
		"Flat tire on station wagon with tapes.  ('Never underestimate the bandwidth of a station wagon full of tapes hurling down the highway' Andrew S. Tannenbaum) "
		"Communications satellite used by the military for star wars."
		"Party-bug in the Aloha protocol."
		"Insert coin for new game"
		"Dew on the telephone lines."
		"Arcserve crashed the server again."
		"Some one needed the powerstrip so they pulled the switch plug."
		"My pony-tail hit the on/off switch on the power strip."
		"Big to little endian conversion error"
		"You can tune a file system but you can't tune a fish (from most tunefs man pages)"
		"Dumb terminal"
		"Zombie processes haunting the computer"
		"Incorrect time synchronization"
		"Defunct processes"
		"Stubborn processes"
		"non-redundant fan failure "
		"monitor VLF leakage"
		"bugs in the RAID"
		"no 'any' key on keyboard"
		"root rot"
		"Backbone Scoliosis"
		"/pub/lunch"
		"excessive collisions & not enough packet ambulances"
		"le0: no carrier: transceiver cable problem?"
		"broadcast packets on wrong frequency"
		"popper unable to process jumbo kernel"
		"NOTICE: alloc: /dev/null: filesystem full"
		"pseudo-user on a pseudo-terminal"
		"Recursive traversal of loopback mount points"
		"Backbone adjustment"
		"OS swapped to disk"
		"vapors from evaporating sticky-note adhesives"
		"sticktion"
		"short leg on process table"
		"multicasts on broken packets"
		"ether leak"
		"Atilla the Hub"
		"endothermal recalibration"
		"filesystem not big enough for Jumbo Kernel Patch"
		"loop found in loop in redundant loopback"
		"system consumed all the paper for paging"
		"permission denied"
		"Reformatting Page. Wait..."
		"..disk or the processor is on fire."
		"SCSI's too wide."
		"Proprietary Information."
		"Just type 'mv * /dev/null'."
		"runaway cat on system."
		"Did you pay the new Support Fee?"
		"We only support a 1200 bps connection."
		"We only support a 28000 bps connection."
		"Me no internet only janitor me just wax floors."
		"I'm sorry a pentium won't do you need an SGI to connect with us."
		"Post-it Note Sludge leaked into the monitor."
		"the curls in your keyboard cord are losing electricity."
		"The monitor needs another box of pixels."
		"RPC_PMAP_FAILURE"
		"kernel panic: write-only-memory (/dev/wom0) capacity exceeded."
		"Write-only-memory subsystem too slow for this machine. Contact your local dealer."
		"Just pick up the phone and give modem connect sounds. 'Well you said we should get more lines so we don't have voice lines.'"
		"Quantum dynamics are affecting the transistors"
		"Police are examining all internet packets in the search for a narco-net-trafficker"
		"We are currently trying a new concept of using a live mouse.  Unfortunately one has yet to survive being hooked up to the computer.....please bear with us."
		"Your mail is being routed through Germany ... and they're censoring us."
		"Only people with names beginning with 'A' are getting mail this week (a la Microsoft)"
		"We didn't pay the Internet bill and it's been cut off."
		"Lightning strikes."
		"Of course it doesn't work. We've performed a software upgrade."
		"Change your language to Finnish."
		"Fluorescent lights are generating negative ions. If turning them off doesn't work take them out and put tin foil on the ends."
		"High nuclear activity in your area."
		"What office are you in? Oh that one.  Did you know that your building was built over the universities first nuclear research site? And wow aren't you the lucky one your office is right over where the core is buried!"
		"The MGs ran out of gas."
		"The UPS doesn't have a battery backup."
		"Recursivity.  Call back if it happens again."
		"Someone thought The Big Red Button was a light switch."
		"The mainframe needs to rest.  It's getting old you know."
		"I'm not sure.  Try calling the Internet's head office -- it's in the book."
		"The lines are all busy (busied out that is -- why let them in to begin with?)."
		"Jan  9 16:41:27 huber su: 'su root' succeeded for .... on /dev/pts/1"
		"It's those computer people in X {city of world}.  They keep stuffing things up."
		"A star wars satellite accidently blew up the WAN."
		"Fatal error right in front of screen"
		"That function is not currently supported but Bill Gates assures us it will be featured in the next upgrade."
		"wrong polarity of neutron flow"
		"Lusers learning curve appears to be fractal"
		"We had to turn off that service to comply with the CDA Bill."
		"Ionization from the air-conditioning"
		"TCP/IP UDP alarm threshold is set too low."
		"Someone is broadcasting pygmy packets and the router doesn't know how to deal with them."
		"The new frame relay network hasn't bedded down the software loop transmitter yet. "
		"Fanout dropping voltage too much try cutting some of those little traces"
		"Plate voltage too low on demodulator tube"
		"You did wha... oh _dear_...."
		"CPU needs bearings repacked"
		"Too many little pins on CPU confusing it bend back and forth until 10-20% are neatly removed. Do _not_ leave metal bits visible!"
		"_Rosin_ core solder? But..."
		"Software uses US measurements but the OS is in metric..."
		"The computer fleetly mouse and all."
		"Your cat tried to eat the mouse."
		"The Borg tried to assimilate your system. Resistance is futile."
		"It must have been the lightning storm we had (yesterday) (last week) (last month)"
		"Due to Federal Budget problems we have been forced to cut back on the number of users able to access the system at one time. (namely none allowed....)"
		"Too much radiation coming from the soil."
		"Unfortunately we have run out of bits/bytes/whatever. Don't worry the next supply will be coming next week."
		"Program load too heavy for processor to lift."
		"Processes running slowly due to weak power supply"
		"Our ISP is having {switchingroutingSMDSframe relay} problems"
		"We've run out of licenses"
		"Interference from lunar radiation"
		"Standing room only on the bus."
		"You need to install an RTFM interface."
		"That would be because the software doesn't work."
		"That's easy to fix but I can't be bothered."
		"Someone's tie is caught in the printer and if anything else gets printed he'll be in it too."
		"We're upgrading /dev/null"
		"The Usenet news is out of date"
		"Our POP server was kidnapped by a weasel."
		"It's stuck in the Web."
		"Your modem doesn't speak English."
		"The mouse escaped."
		"All of the packets are empty."
		"The UPS is on strike."
		"Neutrino overload on the nameserver"
		"Melting hard drives"
		"Someone has messed up the kernel pointers"
		"The kernel license has expired"
		"Netscape has crashed"
		"The cord jumped over and hit the power switch."
		"It was OK before you touched it."
		"Bit rot"
		"U.S. Postal Service"
		"Your Flux Capacitor has gone bad."
		"The Dilithium Crystals need to be rotated."
		"The static electricity routing is acting up..."
		"Traceroute says that there is a routing problem in the backbone.  It's not our problem."
		"The co-locator cannot verify the frame-relay gateway to the ISDN server."
		"High altitude condensation from U.S.A.F prototype aircraft has contaminated the primary subnet mask. Turn off your computer for 9 days to avoid damaging it."
		"Lawn mower blade in your fan need sharpening"
		"Electrons on a bender"
		"Telecommunications is upgrading. "
		"Telecommunications is downgrading."
		"Telecommunications is downshifting."
		"Hard drive sleeping. Let it wake up on it's own..."
		"Interference between the keyboard and the chair."
		"The CPU has shifted and become decentralized."
		"Due to the CDA we no longer have a root account."
		"We ran out of dial tone and we're and waiting for the phone company to deliver another bottle."
		"You must've hit the wrong any key."
		"PCMCIA slave driver"
		"The Token fell out of the ring. Call us when you find it."
		"The hardware bus needs a new token."
		"Too many interrupts"
		"Not enough interrupts"
		"The data on your hard drive is out of balance."
		"Digital Manipulator exceeding velocity parameters"
		"appears to be a Slow/Narrow SCSI-0 Interface problem"
		"microelectronic Riemannian curved-space fault in write-only file system"
		"fractal radiation jamming the backbone"
		"routing problems on the neural net"
		"IRQ-problems with the Un-Interruptible-Power-Supply"
		"CPU-angle has to be adjusted because of vibrations coming from the nearby road"
		"emissions from GSM-phones"
		"CD-ROM server needs recalibration"
		"firewall needs cooling"
		"asynchronous inode failure"
		"transient bus protocol violation"
		"incompatible bit-registration operators"
		"your process is not ISO 9000 compliant"
		"You need to upgrade your VESA local bus to a MasterCard local bus."
		"The recent proliferation of Nuclear Testing"
		"Elves on strike. (Why do they call EMAG Elf Magic)"
		"Internet exceeded Luser level please wait until a luser logs off before attempting to log back on."
		"Your EMAIL is now being delivered by the USPS."
		"Your computer hasn't been returning all the bits it gets from the Internet."
		"You've been infected by the Telescoping Hubble virus."
		"Scheduled global CPU outage"
		"Your Pentium has a heating problem - try cooling it with ice cold water.(Do not turn off your computer you do not want to cool down the Pentium Chip while he isn't working do you?)"
		"Your processor has processed too many instructions.  Turn it off immediately do not type any commands!!"
		"Your packets were eaten by the terminator"
		"Your processor does not develop enough heat."
		"We need a licensed electrician to replace the light bulbs in the computer room."
		"The POP server is out of Coke"
		"Fiber optics caused gas main leak"
		"Server depressed needs Prozac"
		"quantum decoherence"
		"those damn raccoons!"
		"suboptimal routing experience"
		"A plumber is needed the network drain is clogged"
		"50% of the manual is in .pdf readme files"
		"the AA battery in the wallclock sends magnetic interference"
		"the xy axis in the trackball is coordinated with the summer solstice"
		"the butane lighter causes the pincushioning"
		"old inkjet cartridges emanate barium-based fumes"
		"manager in the cable duct"
		"We'll fix that in the next (upgrade update patch release service pack)."
		"HTTPD Error 666 : BOFH was here"
		"HTTPD Error 4004 : very old Intel cpu - insufficient processing power"
		"The ATM board has run out of 10 pound notes.  We are having a whip round to refill it care to contribute ?"
		"Network failure -  call NBC"
		"Having to manually track the satellite."
		"Your/our computer(s) had suffered a memory leak and we are waiting for them to be topped up."
		"The rubber band broke"
		"We're on Token Ring and it looks like the token got loose."
		"Stray Alpha Particles from memory packaging caused Hard Memory Error on Server."
		"paradigm shift...without a clutch"
		"PEBKAC (Problem Exists Between Keyboard And Chair)"
		"The cables are not the same length."
		"Second-system effect."
		"Chewing gum on /dev/sd3c"
		"Boredom in the Kernel."
		"the daemons! the daemons! the terrible daemons!"
		"I'd love to help you -- it's just that the Boss won't let me near the computer. "
		"struck by the Good Times virus"
		"YOU HAVE AN I/O ERROR -> Incompetent Operator error"
		"Your parity check is overdrawn and you're out of cache."
		"Communist revolutionaries taking over the server room and demanding all the computers in the building or they shoot the sysadmin. Poor misguided bofh_stringls."
		"Plasma conduit breach"
		"Out of cards on drive D:"
		"Sand fleas eating the Internet cables"
		"parallel processors running perpendicular today"
		"ATM cell has no roaming feature turned on notebooks can't connect"
		"Webmasters kidnapped by evil cult."
		"Failure to adjust for daylight savings time."
		"Virus transmitted from computer to sysadmins."
		"Virus due to computers having unsafe sex."
		"Incorrectly configured static routes on the corerouters."
		"Forced to support NT servers; sysadmins quit."
		"Suspicious pointer corrupted virtual machine"
		"It's the InterNIC's fault."
		"Root name servers corrupted."
		"Budget cuts forced us to sell all the power cords for the servers."
		"Someone hooked the twisted pair wires into the answering machine."
		"Operators killed by year 2000 bug bite."
		"We've picked COBOL as the language of choice."
		"Operators killed when huge stack of backup tapes fell over."
		"Robotic tape changer mistook operator's tie for a backup tape."
		"Someone was smoking in the computer room and set off the halon systems."
		"Your processor has taken a ride to Heaven's Gate on the UFO behind Hale-Bopp's comet."
		"it's an ID-10-T error"
		"Dyslexics retyping hosts file on servers"
		"The Internet is being scanned for viruses."
		"Your computer's union contract is set to expire at midnight."
		"Bad user karma."
		"/dev/clue was linked to /dev/null"
		"Increased sunspot activity."
		"We already sent around a notice about that."
		"It's union rules. There's nothing we can do about it. Sorry."
		"Interference from the Van Allen Belt."
		"Jupiter is aligned with Mars."
		"Redundant ACLs. "
		"Mail server hit by UniSpammer."
		"T-1's congested due to porn traffic to the news server."
		"Data for intranet got routed through the extranet and landed on the internet."
		"We are a 100% Microsoft Shop."
		"We are Microsoft.  What you are experiencing is not a problem; it is an undocumented feature."
		"Sales staff sold a product we don't offer."
		"Secretary sent chain letter to all 5000 employees."
		"Sysadmin didn't hear pager go off due to loud music from bar-room speakers."
		"Sysadmin accidentally destroyed pager with a large hammer."
		"Sysadmins unavailable because they are in a meeting talking about why they are unavailable so much."
		"Bad cafeteria bofh_stringd landed all the sysadmins in the hospital."
		"Route flapping at the NAP."
		"Computers under water due to SYN flooding."
		"The vulcan-death-grip ping has been applied."
		"Electrical conduits in machine room are melting."
		"Traffic jam on the Information Superhighway."
		"Radial Telemetry Infiltration"
		"Cow-tippers tipped a cow onto the server."
		"tachyon emissions overloading the system"
		"Maintenance window broken"
		"We're out of slots on the server"
		"Computer room being moved.  Our systems are down for the weekend."
		"Sysadmins busy fighting SPAM."
		"Repeated reboots of the system failed to solve problem"
		"Feature was not beta tested"
		"Domain controller not responding"
		"Someone else stole your IP address call the Internet detectives!"
		"It's not RFC-822 compliant."
		"operation failed because: there is no message for this error (#1014)"
		"stop bit received"
		"internet is needed to catch the etherbunny"
		"network down IP packets delivered via UPS"
		"Firmware update in the coffee machine"
		"Temporal anomaly"
		"Mouse has out-of-cheese-error"
		"Borg implants are failing"
		"Borg nanites have infested the server"
		"error: one bad user found in front of screen"
		"Please state the nature of the technical emergency"
		"Internet shut down due to maintenance"
		"Daemon escaped from pentagram"
		"crop circles in the corn shell"
		"sticky bit has come loose"
		"Hot Java has gone cold"
		"Cache miss - please take better aim next time"
		"Hash table has woodworm"
		"Trojan horse ran out of hay"
		"Zombie processes detected machine is haunted."
		"overflow error in /dev/null"
		"Browser's cookie is corrupted -- someone's been nibbling on it."
		"Mailer-daemon is busy burning your message in hell."
		"According to Microsoft it's by design"
		"vi needs to be upgraded to vii"
		"greenpeace free'd the mallocs"
		"Terrorists crashed an airplane into the server room have to remove /bin/laden. (rm -rf /bin/laden)"
		"astropneumatic oscillations in the water-cooling"
		"Somebody ran the operating system through a spelling checker."
		"Rhythmic variations in the voltage reaching the power supply."
		"Keyboard Actuator Failure.  Order and Replace."
		"Packet held up at customs."
		"Propagation delay."
		"High line impedance."
		"Someone set us up the bomb."
		"Power surges on the Underground."
		"Don't worry; it's been deprecated. The new one is worse."
		"Excess condensation in cloud network"
		"It is a layer 8 problem"
		"The math co-processor had an overflow error that leaked out and shorted the RAM"
		"Leap second overloaded RHEL6 servers"
		"DNS server drank too much and had a hiccup"
		"Your machine had the fuses in backwards."
	)
	printf "$(tput bold)$(tput setaf 1)$(shuf -n 1 -e "${EXCUSES[@]}")$(tput sgr0)"
}

function compliment() {
	local COMPLIMENTS=(
		"You’re that “Nothing” when people ask me what I’m thinking about."
		"You look great today."
		"You’re a smart cookie."
		"I bet you make babies smile."
		"You have impeccable manners."
		"I like your style."
		"You have the best laugh."
		"I appreciate you."
		"You are the most perfect you there is."
		"Our system of inside jokes is so advanced that only you and I get it. And I like that."
		"You’re strong."
		"Your perspective is refreshing."
		"You’re an awesome friend."
		"You light up the room."
		"You deserve a hug right now."
		"You should be proud of yourself."
		"You’re more helpful than you realize."
		"You have a great sense of humor."
		"You’ve got all the right moves!"
		"Is that your picture next to “charming” in the dictionary?"
		"Your kindness is a balm to all who encounter it."
		"You’re all that and a super-size bag of chips."
		"On a scale from 1 to 10, you’re an 11."
		"You are brave."
		"You’re even more beautiful on the inside than you are on the outside."
		"You have the courage of your convictions."
		"Aside from food. You’re my favorite."
		"If cartoon bluebirds were real, a bunch of them would be sitting on your shoulders singing right now."
		"You are making a difference."
		"You’re like sunshine on a rainy day."
		"You bring out the best in other people."
		"Your ability to recall random factoids at just the right time is impressive."
		"You’re a great listener."
		"How is it that you always look great, even in sweatpants?"
		"Everything would be better if more people were like you!"
		"I bet you sweat glitter."
		"You were cool way before hipsters were cool."
		"That color is perfect on you."
		"Hanging out with you is always a blast."
		"You always know — and say — exactly what I need to hear when I need to hear it."
		"You smell really good."
		"You may dance like no one’s watching, but everyone’s watching because you’re an amazing dancer!"
		"Being around you makes everything better!"
		"When you say, “I meant to do that,” I totally believe you."
		"When you’re not afraid to be yourself is when you’re most incredible."
		"Colors seem brighter when you’re around."
		"You’re more fun than a ball pit filled with candy. (And seriously, what could be more fun than that?)"
		"That thing you don’t like about yourself is what makes you so interesting."
		"You’re wonderful."
		"Everyday is just BLAH when I don’t see you For reals! (awesome – you are halfway through the list. You’re awesome!)"
		"Jokes are funnier when you tell them."
		"You’re better than a triple-scoop ice cream cone. With sprinkles."
		"Your bellybutton is kind of adorable."
		"Your hair looks stunning."
		"You’re one of a kind!"
		"You’re inspiring."
		"If you were a box of crayons, you’d be the giant name-brand one with the built-in sharpener."
		"You should be thanked more often. So thank you!!"
		"Our community is better because you’re in it."
		"Someone is getting through something hard right now because you’ve got their back."
		"You have the best ideas."
		"You always know how to find that silver lining."
		"Everyone gets knocked down sometimes, but you always get back up and keep going."
		"You’re a candle in the darkness."
		"You’re a great example to others."
		"Being around you is like being on a happy little vacation."
		"You always know just what to say."
		"You’re always learning new things and trying to better yourself, which is awesome."
		"If someone based an Internet meme on you, it would have impeccable grammar."
		"You could survive a Zombie apocalypse."
		"You’re more fun than bubble wrap."
		"When you make a mistake, you fix it."
		"Who raised you? They deserve a medal for a job well done."
		"You’re great at figuring stuff out."
		"Your voice is magnificent."
		"The people you love are lucky to have you in their lives."
		"You’re like a breath of fresh air."
		"You’re gorgeous — and that’s the least interesting thing about you, too."
		"You’re so thoughtful."
		"Your creative potential seems limitless."
		"You’re the coolest person I know. And I consider myself bet friends with like all celebrities, so. . . ."
		"You’re irresistible when you blush."
		"Actions speak louder than words, and yours tell an incredible story."
		"Somehow you make time stop and fly at the same time."
		"When you make up your mind about something, nothing stands in your way."
		"You seem to really know who you are."
		"Any team would be lucky to have you on it."
		"In high school I bet you were voted “most likely to keep being awesome.”"
		"I bet you do the crossword puzzle in ink."
		"Babies and small animals probably love you."
		"If you were a scented candle they’d call it Perfectly Imperfect (and it would smell like summer)."
		"There’s ordinary, and then there’s you."
		"You’re someone’s reason to smile."
		"You’re even better than a unicorn, because you’re real."
		"How do you keep being so funny and making everyone laugh?"
		"You have a good head on your shoulders."
		"Has anyone ever told you that you have great posture?"
		"The way you treasure your loved ones is incredible."
		"You’re really something special."
		"You’re a gift to those around you."
		"You have very smooth hair."
		"You deserve a promotion."
		"Good effort!"
		"What a fine sweater!"
		"I appreciate all of your opinions."
		"I like your style."
		"Your T-shirt smells fresh."
		"I love what you've done with the place."
		"You are like a spring flower; beautiful and vivacious."
		"I am utterly disarmed by your wit."
		"I really enjoy the way you pronounce the word 'ruby'."
		"You complete me."
		"Well done!"
		"I like your Facebook status."
		"That looks nice on you."
		"I like those shoes more than mine."
		"Nice motor control!"
		"You have a good taste in websites."
		"Your mouse told me that you have very soft hands."
		"You are full of youth."
		"I like your jacket."
		"I like the way you move."
		"You have a good web-surfing stance."
		"You should be a poster child for poster children."
		"Nice manners!"
		"I appreciate you more than Santa appreciates chimney grease."
		"I wish I was your mirror."
		"I find you to be a fountain of inspiration."
		"You have perfect bone structure."
		"I disagree with anyone who disagrees with you."
		"Way to go!"
		"Have you been working out?"
		"With your creative wit, I'm sure you could come up with better compliments than me."
		"I like your socks."
		"You are so charming."
		"Your cooking reminds me of my mother's."
		"You're tremendous!"
		"You deserve a compliment!"
		"Hello, good looking."
		"Your smile is breath taking."
		"How do you get your hair to look that great?"
		"You are quite strapping."
		"I am grateful to be blessed by your presence."
		"Say, aren't you that famous model from TV?"
		"Take a break; you've earned it."
		"Your life is so interesting!"
		"The sound of your voice sends tingles of joy down my back."
		"I enjoy spending time with you."
		"I would share my dessert with you."
		"You can have the last bite."
		"May I have this dance?"
		"I would love to visit you, but I live on the Internet."
		"I love the way you click."
		"You're invited to my birthday party."
		"All of your ideas are brilliant!"
		"If I freeze, it's not a computer virus.  I was just stunned by your beauty."
		"You're spontaneous, and I love it!"
		"You should try out for everything."
		"You make my data circuits skip a beat."
		"You are the gravy to my mashed potatoes."
		"You get an A+!"
		"I'm jealous of the other websites you visit, because I enjoy seeing you so much!"
		"I would enjoy a roadtrip with you."
		"If I had to choose between you or Mr. Rogers, it would be you."
		"I like you more than the smell of Grandma's home-made apple pies."
		"You would look good in glasses OR contacts."
		"Let's do this again sometime."
		"You could go longer without a shower than most people."
		"I feel the need to impress you."
		"I would trust you to pick out a pet fish for me."
		"I'm glad we met."
		"Do that again!"
		"Will you sign my yearbook?"
		"You're so smart!"
		"We should start a band."
		"You're cooler than ice-skating Fonzi."
		"I made this website for you."
		"I heard you make really good French Toast."
		"You're cooler than Pirates and Ninjas combined."
		"I like your pants."
		"You're pretty groovy, dude."
		"When I grow up, I want to be just like you."
		"I told all my friends about how cool you are."
		"You can play any prank, and get away with it."
		"You have ten of the best fingers I have ever seen!"
		"I can tell that we are gonna be friends."
		"I just want to gobble you up!"
		"You're sweeter than than a bucket of bon-bons!"
		"Treat yourself to another compliment!"
		"You're pretty high on my list of people with whom I would want to be stranded on an island."
		"You're #1 in my book!"
		"Well played."
		"You are well groomed."
		"You could probably lead a rebellion."
		"Is it hot in here or is it just you?"
		"<3"
		"You are more fun than a Japanese steakhouse."
		"Your voice is more soothing than Morgan Freeman's."
		"I like your sleeves. They're real big."
		"You could be drinking whole milk if you wanted to."
		"You're so beautiful, you make me walk into things when I look at you."
		"I support all of your decisions."
		"You are as fun as a hot tub full of chocolate pudding."
		"I usually don't say this on a first date, but will you marry me?"
		"I don't speak much English, but with you all I really need to say is beautiful."
		"Being awesome is hard, but you'll manage."
		"Your skin is radiant."
		"You will still be beautiful when you get older."
		"You could survive a zombie apocalypse."
		"You make me :)"
		"I wish I could move your furniture."
		"I think about you while I'm on the toilet."
		"You're so rad."
		"You're more fun than a barrel of monkeys."
		"You're nicer than a day on the beach."
		"Your glass is the fullest."
		"I find you very relevant."
		"You look so perfect."
		"The only difference between exceptional and amazing is you."
		"Last night I had the hiccups, and the only thing that comforted me to sleep was repeating your name over and over."
		"I like your pearly whites!"
		"Your eyebrows really make your pretty eyes stand out."
		"Shall I compare thee to a summer's day?  Thou art more lovely and more temperate."
		"I love you more than bacon!"
		"You intrigue me."
		"You make me think of beautiful things, like strawberries."
		"I would share my fruit Gushers with you."
		"You're more aesthetically pleasant to look at than that one green color on this website."
		"Even though this goes against everything I know, I think I'm in love with you."
		"You're more fun than bubble wrap."
		"Your smile could illuminate the depths of the ocean."
		"You make babies smile."
		"You make the gloomy days a little less gloomy."
		"You are warmer than a Snuggie."
		"You make me feel like I am on top of the world."
		"Playing video games with you would be fun."
		"Let's never stop hanging out."
		"You're more cuddly than the Downy Bear."
		"I would do your taxes any day."
		"You are a bucket of awesome."
		"You are the star of my daydreams."
		"If you really wanted to, you could probably get a bird to land on your shoulder and hang out with you."
		"My mom always asks me why I can't be more like you."
		"You look great in this or any other light."
		"You listen to the coolest music."
		"You and Chuck Norris are on equal levels."
		"Your body fat percentage is perfectly suited for your height."
		"I am having trouble coming up with a compliment worthy enough for you."
		"If we were playing kickball, I'd pick you first."
		"You're cooler than ice on the rocks."
		"You're the bee's knees."
		"I wish I could choose your handwriting as a font."
		"You definitely know the difference between your and you're."
		"You have good taste."
		"I named all my appliances after you."
		"Your mind is a maze of amazing!"
		"Don't worry about procrastinating on your studies, I know you'll do great!"
		"I like your style!"
		"Hi, I'd like to know why you're so beautiful."
		"If I could count the seconds I think about you, I will die in the process!"
		"If you were in a chemistry class with me, it would be 10x less boring."
		"If you broke your arm, I would carry your books for you."
		"I love the way your eyes crinkle at the corners when you smile."
		"You make me want to be the person I am capable of being."
		"You're a skilled driver."
		"You are the rare catalyst to my volatile compound."
		"You're a tall glass of water!"
		"I'd like to kiss you. Often."
		"You are the wind beneath my wings."
		"Looking at you makes my foot cramps go away instantaneously."
		"I like your face."
		"You are a champ!"
		"You are infatuating."
		"Even my cat likes you."
		"There isn't a thing about you that I don't like."
		"You're so cool, that on a scale of from 1-10, you're elevendyseven."
		"OH, you OWN that ponytail."
		"Your shoes are untied. But for you, it's cool."
		"You have the best laugh ever."
		"We would enjoy a cookout with you!"
		"Your name is fun to say."
		"I love you more than a drunk college student loves tacos."
		"My camera isn't worthy to take your picture."
		"You are the sugar on my rice krispies."
		"Nice belt!"
		"I could hang out with you for a solid year and never get tired of you."
		"You're real happening in a far out way."
		"I bet you could take a punch from Mike Tyson."
		"Your feet are perfect size!"
		"You have very nice teeth."
		"Can you teach me how to be as awesome as you?"
		"Our awkward silences aren't even awkward."
		"Don't worry. You'll do great."
		"I enjoy you more than a good sneeze. A GOOD one."
		"You could invent words and people would use them."
		"You have powerful sweaters."
		"If you were around, I would enjoy doing my taxes."
		"You look like you like to rock."
		"You are better than unicorns and sparkles combined!"
		"You are the watermelon in my fruit salad. Yum!"
		"I dig you."
		"You look better whether the lights are on or off."
		"I am enchanted to meet you."
		"I bet even your farts smell good."
		"I would trust my children with you."
		"You make me forget what I was going to..."
		"Your smile makes me smile."
		"I'd wake up for an 8 a.m. class just so I could sit next to you."
		"You have the moves like Jagger."
		"You're so hot that you denature my proteins."
		"All I want for Christmas is you!"
		"You are the world's greatest hugger."
		"You have a perfectly symmetrical face."
		"If you were in a movie you wouldn't get killed off."
		"Your red ruby lips and wiggly hips make me do flips!"
		"I definitely wouldn't kick you out of bed."
		"They should name an ice cream flavor after you."
		"You're the salsa to my tortilla chips. You spice up my life!"
		"You smell nice."
		"You don't need make-up, make-up needs you."
		"Me without you is like a nerd without braces, a shoe with out laces, asentencewithoutspaces."
		"Just knowing someone as cool as you will read this makes me smile."
		"I would volunteer to take your place in the Hunger Games."
		"If I had a nickel for everytime you did something stupid, I'd be broke!"
		"I'd let you steal the white part of my Oreo."
		"I'd trust you to perform open heart surgery on me... blindfolded!"
		"Nice butt! - According to your toilet seat"
		"Perfume strives to smell like you."
		"I've had the time of my life, and I owe it all to you!"
		"The Force is strong with you."
		"I like the way your nostrils are placed on your nose."
		"I would hold the elevator doors open for you if they were closing."
		"Your every thought and motion contributes to the beauty of the universe."
		"You make me want to frolic in a field."
	)
	printf "$(tput setaf 2)$(shuf -n 1 -e "${COMPLIMENTS[@]}")$(tput sgr0)"
}

alias insult_cow='insult | cowthink'
alias excuse_cow='excuse | cowthink'
alias compliment_cow='compliment | cowthink'
